2022-11-06 19:30:17,555 INFO    MainThread:8459 [wandb_setup.py:_flush():76] Configure stats pid to 8459
2022-11-06 19:30:17,555 INFO    MainThread:8459 [wandb_setup.py:_flush():76] Loading settings from /Users/vlourenco/.config/wandb/settings
2022-11-06 19:30:17,555 INFO    MainThread:8459 [wandb_setup.py:_flush():76] Loading settings from /Users/vlourenco/Documents/GitHub/EEG_MIB/Organized/wandb/settings
2022-11-06 19:30:17,555 INFO    MainThread:8459 [wandb_setup.py:_flush():76] Loading settings from environment variables: {'_require_service': 'True'}
2022-11-06 19:30:17,555 INFO    MainThread:8459 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program_relpath': 'Organized/train.py', 'program': '/Users/vlourenco/Documents/GitHub/EEG_MIB/Organized/train.py'}
2022-11-06 19:30:17,555 INFO    MainThread:8459 [wandb_init.py:_log_setup():461] Logging user logs to /Users/vlourenco/Documents/GitHub/EEG_MIB/Organized/wandb/run-20221106_193017-2y6pskle/logs/debug.log
2022-11-06 19:30:17,555 INFO    MainThread:8459 [wandb_init.py:_log_setup():462] Logging internal logs to /Users/vlourenco/Documents/GitHub/EEG_MIB/Organized/wandb/run-20221106_193017-2y6pskle/logs/debug-internal.log
2022-11-06 19:30:17,555 INFO    MainThread:8459 [wandb_init.py:init():495] calling init triggers
2022-11-06 19:30:17,556 INFO    MainThread:8459 [wandb_init.py:init():498] wandb.init called with sweep_config: {}
config: {}
2022-11-06 19:30:17,556 INFO    MainThread:8459 [wandb_init.py:init():514] re-initializing run, found existing run on stack: zce6aqyj
2022-11-06 19:30:17,556 INFO    MainThread:8459 [wandb_run.py:_finish():1728] finishing run visilvestre/EEGNet_With_Accuracy/zce6aqyj
2022-11-06 19:30:17,556 INFO    MainThread:8459 [jupyter.py:save_history():435] not saving jupyter history
2022-11-06 19:30:17,556 INFO    MainThread:8459 [jupyter.py:save_ipynb():377] not saving jupyter notebook
2022-11-06 19:30:17,556 INFO    MainThread:8459 [wandb_init.py:_jupyter_teardown():393] cleaning up jupyter logic
2022-11-06 19:30:17,556 INFO    MainThread:8459 [wandb_run.py:_atexit_cleanup():1931] got exitcode: 0
2022-11-06 19:30:17,556 INFO    MainThread:8459 [wandb_run.py:_restore():1914] restore
2022-11-06 19:30:17,556 INFO    MainThread:8459 [wandb_run.py:_restore():1920] restore done
2022-11-06 19:30:17,558 INFO    MainThread:8459 [wandb_run.py:_on_finish():2221] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 742
  total_bytes: 742
}

2022-11-06 19:30:18,844 INFO    MainThread:8459 [wandb_run.py:_on_finish():2221] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 742
  total_bytes: 742
}

2022-11-06 19:30:19,180 INFO    MainThread:8459 [wandb_run.py:_on_finish():2221] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 742
  total_bytes: 742
}

2022-11-06 19:30:21,567 INFO    MainThread:8459 [wandb_run.py:_on_finish():2221] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 742
  total_bytes: 742
}

2022-11-06 19:30:22,390 INFO    MainThread:8459 [wandb_run.py:_on_finish():2221] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 742
  total_bytes: 20014
}

2022-11-06 19:30:22,496 INFO    MainThread:8459 [wandb_run.py:_on_finish():2221] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 742
  total_bytes: 20014
}

2022-11-06 19:30:22,603 INFO    MainThread:8459 [wandb_run.py:_on_finish():2221] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 742
  total_bytes: 20014
}

2022-11-06 19:30:22,710 INFO    MainThread:8459 [wandb_run.py:_on_finish():2221] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 20014
  total_bytes: 20014
}

2022-11-06 19:30:22,816 INFO    MainThread:8459 [wandb_run.py:_on_finish():2221] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 20014
  total_bytes: 20014
}

2022-11-06 19:30:22,920 INFO    MainThread:8459 [wandb_run.py:_on_finish():2221] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 20014
  total_bytes: 20014
}

2022-11-06 19:30:23,027 INFO    MainThread:8459 [wandb_run.py:_on_finish():2221] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 20014
  total_bytes: 20014
}

2022-11-06 19:30:23,137 INFO    MainThread:8459 [wandb_run.py:_on_finish():2221] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 20014
  total_bytes: 20014
}

2022-11-06 19:30:23,656 INFO    MainThread:8459 [wandb_run.py:_on_finish():2221] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 20014
  total_bytes: 20014
}

2022-11-06 19:30:23,981 INFO    MainThread:8459 [wandb_run.py:_on_finish():2221] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 20014
  total_bytes: 20014
}
local_info {
}

2022-11-06 19:30:25,089 INFO    MainThread:8459 [wandb_run.py:_footer_history_summary_info():3305] rendering history
2022-11-06 19:30:25,090 INFO    MainThread:8459 [wandb_run.py:_footer_history_summary_info():3337] rendering summary
2022-11-06 19:30:25,092 INFO    MainThread:8459 [wandb_run.py:_footer_sync_info():3261] logging synced files
2022-11-06 19:30:25,093 INFO    MainThread:8459 [wandb_init.py:init():548] starting backend
2022-11-06 19:30:25,093 INFO    MainThread:8459 [wandb_init.py:init():552] setting up manager
2022-11-06 19:30:25,094 INFO    MainThread:8459 [backend.py:_multiprocessing_setup():97] multiprocessing start_methods=spawn,fork,forkserver, using: spawn
2022-11-06 19:30:25,094 INFO    MainThread:8459 [wandb_init.py:init():558] backend started and connected
2022-11-06 19:30:25,095 INFO    MainThread:8459 [wandb_run.py:_label_probe_notebook():1105] probe notebook
2022-11-06 19:30:25,095 INFO    MainThread:8459 [wandb_run.py:_label_probe_notebook():1115] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2022-11-06 19:30:25,095 INFO    MainThread:8459 [wandb_init.py:init():636] updated telemetry
2022-11-06 19:30:25,111 INFO    MainThread:8459 [wandb_init.py:init():667] communicating run to backend with 30 second timeout
2022-11-06 19:30:26,803 INFO    MainThread:8459 [wandb_run.py:_on_init():1982] communicating current version
2022-11-06 19:30:26,907 INFO    MainThread:8459 [wandb_run.py:_on_init():1986] got version response upgrade_message: "wandb version 0.13.5 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2022-11-06 19:30:26,907 INFO    MainThread:8459 [wandb_init.py:init():700] starting run threads in backend
2022-11-06 19:30:30,894 INFO    MainThread:8459 [wandb_run.py:_console_start():1962] atexit reg
2022-11-06 19:30:30,894 INFO    MainThread:8459 [wandb_run.py:_redirect():1820] redirect: SettingsConsole.WRAP_RAW
2022-11-06 19:30:30,894 INFO    MainThread:8459 [wandb_run.py:_redirect():1885] Wrapping output streams.
2022-11-06 19:30:30,894 INFO    MainThread:8459 [wandb_run.py:_redirect():1907] Redirects installed.
2022-11-06 19:30:30,895 INFO    MainThread:8459 [wandb_init.py:init():732] run started, returning control to user process
